### ISSUE TITLE
Some captions are just Emoji

### ISSUE THREAD

**Issue by viyjy** [LAION-AI/Discord-Scrapers#3]
Hi, thanks for providing this dataset which is very useful. I have two questions regarding this dataset:
(1) I found that some captions are just Emoji (see the attached image). How come that DALLE 3 can generate images based on these Emoji and should we include them in this dataset?
(2) https://huggingface.co/datasets/laion/dalle-3-dataset/tree/main/data is updated frequently. If I want to use this dataset, should I wait for a stable version or just use any snapshot is ok? Thanks

![image](https://github.com/LAION-AI/Discord-Scrapers/assets/20442927/4005af2e-8b21-4282-9dbb-e818cac2e213)

**Comment by ZachNagengast** [comment]
I think any snapshot is okay, It'll be increasing over time as more people add their entries to the discord channel https://discord.com/channels/823813159592001537/1158354590463447092

As for the emojis, i suppose DALLE 3 was trained on emojis so I consider them valid samples since the images appear to be pretty well related.

**Comment by viyjy** [comment]
get it, thanks!
